#!/usr/bin/env python3
import os
mydir = os.path.dirname(os.path.realpath(__file__))
if __name__ == '__main__':
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument('uuid', help='Unique ID of the device')
    args = parser.parse_args()
    program = os.path.join(mydir, 'tunnel-client')
    print(f'using an android device: {args.uuid}')
    os.system(f'{program} {args.uuid} 5555 7912')
